// Auto-generated by Lead Hunter — 2026-02-24T14:57:32.180Z
// Копирай тези таргети в b2b-agency-runner.ts

export const autoTargets = [
        {
            name: "CEO",
            company: "SoftUni",
            domain: "softuni.bg",
            email: "university@softuni.bg",
            role: "Decision Maker",
            painPoint: "Need AI-powered tools for teaching automation"
        },
        {
            name: "CEO",
            company: "DevriX",
            domain: "devrix.com",
            email: "contact@devrix.com",
            role: "Decision Maker",
            painPoint: "WordPress and web app testing needs automation"
        },
        {
            name: "CEO",
            company: "Xplora",
            domain: "xplora.bg",
            email: "human@xplora.bg",
            role: "Decision Maker",
            painPoint: "Lead generation for clients is manual and slow"
        },
        {
            name: "CEO",
            company: "Netinfo",
            domain: "netinfo.bg",
            email: "reklama@netinfo.bg",
            role: "Decision Maker",
            painPoint: "No automated website security scanning for client reports"
        },
        {
            name: "CEO",
            company: "Hop Online",
            domain: "hop.bg",
            email: "support@hop.bg",
            role: "Decision Maker",
            painPoint: "SEO audits and technical analysis are time-consuming"
        },
        {
            name: "CEO",
            company: "SpeedFlow",
            domain: "speedflow.bg",
            email: "info@speedflow.bg",
            role: "Decision Maker",
            painPoint: "Need automated lead generation tools for B2B clients"
        },
        {
            name: "CEO",
            company: "Stenik",
            domain: "stenik.bg",
            email: "office@stenik.bg",
            role: "Decision Maker",
            painPoint: "E-commerce clients need automated security and performance checks"
        },
        {
            name: "CEO",
            company: "Payhawk",
            domain: "payhawk.com",
            email: "support@payhawk.com",
            role: "Decision Maker",
            painPoint: "Need advanced risk management and fraud detection"
        },
        {
            name: "CEO",
            company: "Nexo",
            domain: "nexo.com",
            email: "support@nexo.com",
            role: "Decision Maker",
            painPoint: "Crypto lending needs real-time arbitrage and risk analysis"
        },
        {
            name: "CEO",
            company: "SumUp",
            domain: "sumup.com",
            email: "support@sumup.com",
            role: "Decision Maker",
            painPoint: "Payment processing needs low-latency optimization"
        },
        {
            name: "CEO",
            company: "myPOS",
            domain: "mypos.com",
            email: "get-mypos-get-paid-sm@2x.webp",
            role: "Decision Maker",
            painPoint: "POS infrastructure needs performance monitoring and load testing"
        },
        {
            name: "CEO",
            company: "ICan",
            domain: "icanpreneur.com",
            email: "info@icanpreneur.com",
            role: "Decision Maker",
            painPoint: "Startup analytics platform needs AI insights"
        }
];
