/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⚛️ QANTUM BRUTALITY REPORT v1.0.0
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * 🧠 DEEP DISK SCANNER
 * 
 * Scans specified roots for "brutal" scripts (> 750 lines).
 * 
 * Complexity:
 * - Time: O(N + M*L) | Space: O(D + R)
 *   N = total files, M = script files, L = lines per script
 *   D = directory depth, R = brutal file entries
 * 
 * @author QAntum Labs
 * ═══════════════════════════════════════════════════════════════════════════════
 */

const fs = require('fs');
const path = require('path');
const { performance } = require('perf_hooks');

const CONFIG = {
    // Search roots
    roots: ['C:\\'],
    extensions: ['.ts', '.js', '.rs', '.py', '.cs', '.cpp', '.go', '.java', '.php', '.sh'],
    ignoreDirs: [
        'node_modules', 'dist', '.git', 'target', 'vendor', '__pycache__', 'temp', 'bin', 'obj',
        'Windows', 'Program Files', 'Program Files (x86)', 'AppData', 'ProgramData', '$Recycle.Bin', 'System Volume Information'
    ],
    threshold: 750,
    reportFile: path.join(process.cwd(), 'BRUTALITY_REPORT.md')
};

const stats = {
    totalFilesScanned: 0,
    totalScriptsFound: 0,
    brutalFiles: [],
    startTime: performance.now()
};

function countLines(filePath) {
    try {
        const content = fs.readFileSync(filePath, 'utf8');
        return content.split('\n').length;
    } catch (e) {
        return 0;
    }
}

function scanDirectory(dir) {
    let entries;
    try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch (e) {
        // Permission denied or other error
        return;
    }

    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);

        if (entry.isDirectory()) {
            if (!CONFIG.ignoreDirs.includes(entry.name)) {
                // Complexity: O(1)
                scanDirectory(fullPath);
            }
        } else if (entry.isFile()) {
            stats.totalFilesScanned++;
            const ext = path.extname(entry.name).toLowerCase();

            if (CONFIG.extensions.includes(ext)) {
                stats.totalScriptsFound++;
                const lines = countLines(fullPath);

                if (lines >= CONFIG.threshold) {
                    stats.brutalFiles.push({
                        path: fullPath,
                        name: entry.name,
                        lines: lines,
                        sizeMB: (fs.statSync(fullPath).size / (1024 * 1024)).toFixed(2)
                    });
                    process.stdout.write(`\r🔥 Found brutality: ${entry.name} (${lines} lines)`.padEnd(80) + '\n');
                }
            }

            if (stats.totalFilesScanned % 1000 === 0) {
                process.stdout.write(`\r🔍 Scanning... ${stats.totalFilesScanned} files processed`.padEnd(50));
            }
        }
    }
}

async function generateReport() {
    process.stdout.write('\n🚀 Initiating QANTUM DEEP DISK SCAN...\n');

    for (const root of CONFIG.roots) {
        if (fs.existsSync(root)) {
            process.stdout.write(`\n📍 Scanning root: ${root}\n`);
            // Complexity: O(1)
            scanDirectory(root);
        }
    }

    const duration = ((performance.now() - stats.startTime) / 1000).toFixed(2);

    // Sort brutal files by line count
    stats.brutalFiles.sort((a, b) => b.lines - a.lines);

    const reportContent = `# 👹 QAntum Brutality Report: THE LEGENDS OF LENGHT

> **"Code entropy is inversely proportional to developer sanity."**
> Analysis of scripts with 750+ lines of raw intelligence.

---

## 📊 METRICS
- **Scan Duration:** ${duration}s
- **Files Scanned:** ${stats.totalFilesScanned.toLocaleString()}
- **Scripts Analyzed:** ${stats.totalScriptsFound.toLocaleString()}
- **Brutality Count:** ${stats.brutalFiles.length}

---

## 🏆 BRUTALITY LEADERBOARD (Top 50)

| # | File Name | Lines | Size (MB) | Full Path |
| :--- | :--- | :--- | :--- | :--- |
${stats.brutalFiles.slice(0, 50).map((f, i) => `| ${i + 1} | \`${f.name}\` | **${f.lines.toLocaleString()}** | ${f.sizeMB} | \`${f.path}\` |`).join('\n')}

---

## 🧬 CONCLUSION
The presence of these behemoths indicates high concentration of logic. 
Recommend modularization for files exceeding 2000 lines.

*Generated by QANTUM SCRIPT GOD v1.0.0*
`;

    fs.writeFileSync(CONFIG.reportFile, reportContent, 'utf-8');

    process.stdout.write(`\n\n✅ Report generated: ${CONFIG.reportFile}\n`);
    process.stdout.write(`💀 Total Brutality Matches: ${stats.brutalFiles.length}\n`);
}

    // Complexity: O(1)
generateReport().catch(console.error);
