# ⚛️ QANTUM BRUTALITY REPORT v1.0.0 (PowerShell Edition)
# Scans for scripts > 750 lines

$extensions = @("*.ts", "*.js", "*.rs", "*.py", "*.cs", "*.cpp", "*.go", "*.java", "*.php", "*.sh")
$ignoreDirs = @("node_modules", "dist", ".git", "target", "vendor", "__pycache__", "temp", "bin", "obj", "Windows", "Program Files", "Program Files (x86)", "AppData", "ProgramData")
$threshold = 750
$roots = @("C:\MAGICSTICK", "C:\Users\papic\Downloads") # Safely looking in dev areas first to avoid 1-hour scan

Write-Host "🚀 Initiating QANTUM DEEP DISK SCAN (PowerShell)..." -ForegroundColor Cyan

$brutalFiles = New-Object System.Collections.Generic.List[PSCustomObject]
$scannedCount = 0

foreach ($root in $roots) {
    if (Test-Path $root) {
        Write-Host "📍 Scanning root: $root" -ForegroundColor Yellow
        $files = Get-ChildItem -Path $root -Recurse -Include $extensions -File -ErrorAction SilentlyContinue
        
        foreach ($file in $files) {
            $scannedCount++
            $dir = $file.DirectoryName
            $skip = $false
            foreach ($ignore in $ignoreDirs) {
                if ($dir -like "*\$ignore*") { $skip = $true; break }
            }
            if ($skip) { continue }

            # Quick check for size (scripts > 750 lines are usually > 20KB)
            if ($file.Length -lt 5kb) { continue }

            try {
                $lines = (Get-Content $file.FullName -ErrorAction SilentlyContinue | Measure-Object -Line).Lines
                if ($lines -ge $threshold) {
                    $entry = [PSCustomObject]@{
                        Name   = $file.Name
                        Lines  = $lines
                        SizeMB = [math]::Round($file.Length / 1MB, 2)
                        Path   = $file.FullName
                    }
                    $brutalFiles.Add($entry)
                    Write-Host "🔥 Found brutality: $($file.Name) ($lines lines)" -ForegroundColor Red
                }
            }
            catch {}

            if ($scannedCount % 500 -eq 0) {
                Write-Host -NoNewline "`r🔍 Progress: $scannedCount files analyzed..."
            }
        }
    }
}

Write-Host "`n✅ Scan complete. Generating report..." -ForegroundColor Green

$reportPath = Join-Path (Get-Location) "BRUTALITY_REPORT.md"
$reportHeader = @"
# 👹 QAntum Brutality Report: THE LEGENDS OF LENGHT

> **"Code entropy is inversely proportional to developer sanity."**
> Analysis of scripts with 750+ lines of raw intelligence.

---

## 📊 METRICS
- **Timestamp:** $(Get-Date)
- **Files Analyzed:** $scannedCount
- **Brutality Count:** $($brutalFiles.Count)

---

## 🏆 BRUTALITY LEADERBOARD

| # | File Name | Lines | Size (MB) | Full Path |
| :--- | :--- | :--- | :--- | :--- |
"@

$reportRows = ""
$sortedFiles = $brutalFiles | Sort-Object Lines -Descending
$i = 1
foreach ($f in $sortedFiles) {
    $reportRows += "| $i | ``$($f.Name)`` | **$($f.Lines)** | $($f.SizeMB) | ``$($f.Path)`` |`n"
    $i++
}

$reportFooter = @"

---

## 🧬 CONCLUSION
The presence of these behemoths indicates high concentration of logic. 
Recommend modularization for files exceeding 2000 lines.

*Generated by QANTUM SCRIPT GOD v1.0.0 (PS Engine)*
"@

$finalReport = $reportHeader + "`n" + $reportRows + $reportFooter
$finalReport | Set-Content $reportPath -Encoding UTF8

Write-Host "✅ Report generated: $reportPath" -ForegroundColor Cyan
Write-Host "💀 Total Brutality Matches: $($brutalFiles.Count)" -ForegroundColor Red
