/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface TestCase {
  id: string
  name: string
  code: string
  timeoutMs: number
}
export interface ExecutionResult {
  testId: string
  success: boolean
  durationMs: number
  output: string
  error?: string
}
export interface ExecutorMetrics {
  totalExecuted: number
  successes: number
  failures: number
  avgDurationMs: number
  throughputPerSec: number
}
export declare class SwarmExecutor {
  /** Complexity: O(1) */
  constructor(maxParallel: number)
  /** Complexity: O(N) where N = tests.len() (parallelized via Rayon) */
  executeParallel(tests: Array<TestCase>): Array<ExecutionResult>
  /** Complexity: O(1) */
  getMetrics(): ExecutorMetrics
}
