/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * QAntum v26.0 "Sovereign Nexus"
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * @copyright 2025 Димитър Продромов (Dimitar Prodromov). All Rights Reserved.
 * @license PROPRIETARY AND CONFIDENTIAL
 * 
 * This file is part of QAntum.
 * Unauthorized copying, modification, distribution, or use of this file,
 * via any medium, is strictly prohibited without express written permission.
 * 
 * For licensing inquiries: dimitar.prodromov@QAntum.dev
 * ═══════════════════════════════════════════════════════════════════════════════
 */

import { EventEmitter } from 'node:events';

// ═══════════════════════════════════════════════════════════════════════════════
// 🔗 THE NEXUS COORDINATOR - Inter-Agent Intelligence
// ═══════════════════════════════════════════════════════════════════════════════
// Manages real-time communication between QANTUM (The Shield - defensive QA)
// and CyberCody (The Sword - offensive security testing).
// Implements Autonomous Feedback Loop for vulnerability → test → patch cycle.
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Agent role identifiers
 */
export type AgentRole = 'shield' | 'sword' | 'surgeon' | 'oracle';

/**
 * Vulnerability severity levels
 */
export type VulnerabilitySeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

/**
 * Vulnerability types detected by CyberCody (Sword)
 */
export type VulnerabilityType =
  | 'sqli'          // SQL Injection
  | 'xss'           // Cross-Site Scripting
  | 'bola'          // Broken Object Level Authorization
  | 'csrf'          // Cross-Site Request Forgery
  | 'ssrf'          // Server-Side Request Forgery
  | 'rce'           // Remote Code Execution
  | 'idor'          // Insecure Direct Object Reference
  | 'auth_bypass'   // Authentication Bypass
  | 'info_leak'     // Information Disclosure
  | 'config_error'; // Security Misconfiguration

/**
 * Detected vulnerability from CyberCody
 */
export interface DetectedVulnerability {
  /** Unique vulnerability identifier */
  id: string;
  /** Vulnerability type */
  type: VulnerabilityType;
  /** Severity level */
  severity: VulnerabilitySeverity;
  /** Affected endpoint or component */
  target: string;
  /** Proof of concept payload */
  payload: string;
  /** HTTP method used */
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
  /** Response indicating vulnerability */
  evidence: string;
  /** CVSS score estimate */
  cvssScore: number;
  /** Detection timestamp */
  detectedAt: Date;
  /** CWE reference if known */
  cweId?: string;
}

/**
 * Regression test generated by Shield
 */
export interface RegressionTest {
  /** Unique test identifier */
  id: string;
  /** Associated vulnerability ID */
  vulnerabilityId: string;
  /** Test name */
  name: string;
  /** Test code (TypeScript/Playwright) */
  code: string;
  /** Expected behavior after fix */
  expectedBehavior: string;
  /** Test assertions */
  assertions: string[];
  /** Generated timestamp */
  generatedAt: Date;
}

/**
 * Security patch generated by Surgeon
 */
export interface SecurityPatch {
  /** Unique patch identifier */
  id: string;
  /** Associated vulnerability ID */
  vulnerabilityId: string;
  /** Affected file path */
  filePath: string;
  /** Original code snippet */
  originalCode: string;
  /** Patched code snippet */
  patchedCode: string;
  /** Patch description */
  description: string;
  /** Validation status */
  validated: boolean;
  /** Generated timestamp */
  generatedAt: Date;
}

/**
 * Feedback loop cycle result
 */
export interface FeedbackCycleResult {
  /** Cycle identifier */
  cycleId: string;
  /** Original vulnerability */
  vulnerability: DetectedVulnerability;
  /** Generated regression test */
  regressionTest: RegressionTest;
  /** Generated security patch */
  securityPatch: SecurityPatch;
  /** Patch validation result */
  patchValidated: boolean;
  /** Total cycle duration in ms */
  duration: number;
  /** Timestamp */
  completedAt: Date;
}

/**
 * Nexus Coordinator configuration
 */
export interface NexusCoordinatorConfig {
  /** Enable verbose logging */
  verbose?: boolean;
  /** Maximum concurrent feedback loops */
  maxConcurrentCycles?: number;
  /** Timeout for patch generation in ms */
  patchTimeout?: number;
  /** Enable automatic patch validation */
  autoValidate?: boolean;
  /** Minimum severity to trigger feedback loop */
  minSeverityForLoop?: VulnerabilitySeverity;
  /** Custom AI model for code generation */
  aiModel?: 'cloud' | 'local';
}

/**
 * Nexus message for inter-agent communication
 */
export interface NexusMessage {
  /** Message ID */
  id: string;
  /** Source agent */
  from: AgentRole;
  /** Target agent */
  to: AgentRole;
  /** Message type */
  type: 'vulnerability' | 'test' | 'patch' | 'validation' | 'status';
  /** Message payload */
  payload: unknown;
  /** Priority level */
  priority: 'critical' | 'high' | 'normal' | 'low';
  /** Timestamp */
  timestamp: Date;
}

/**
 * Nexus Coordinator statistics
 */
export interface NexusStats {
  /** Total vulnerabilities processed */
  vulnerabilitiesProcessed: number;
  /** Total regression tests generated */
  testsGenerated: number;
  /** Total patches generated */
  patchesGenerated: number;
  /** Successful patch validations */
  validatedPatches: number;
  /** Active feedback cycles */
  activeCycles: number;
  /** Average cycle duration in ms */
  avgCycleDuration: number;
  /** Uptime in ms */
  uptime: number;
}

// ═══════════════════════════════════════════════════════════════════════════════
// 🔗 NEXUS COORDINATOR CLASS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * NexusCoordinator - The Inter-Agent Intelligence Hub
 * 
 * Coordinates the autonomous feedback loop between:
 * - QANTUM (Shield): Generates regression tests for vulnerabilities
 * - CyberCody (Sword): Detects security vulnerabilities
 * - Surgeon: Generates and validates security patches
 * - Oracle: Provides AI-powered analysis and recommendations
 * 
 * When CyberCody detects a vulnerability (SQLi, BOLA, etc.), the Nexus:
 * 1. Triggers Shield to generate a regression test
 * 2. Triggers Surgeon to generate a security patch
 * 3. Validates the patch using the regression test
 * 4. Reports the complete cycle result
 * 
 * @example
 * ```typescript
 * const nexus = new NexusCoordinator({ verbose: true });
 * await nexus.start();
 * 
 * // When CyberCody detects a vulnerability
 * const result = await nexus.processFeedbackLoop(vulnerability);
 * console.log(`Patch validated: ${result.patchValidated}`);
 * ```
 */
export class NexusCoordinator extends EventEmitter {
  private config: Required<NexusCoordinatorConfig>;
  private isRunning: boolean = false;
  private startTime: number = 0;
  private messageQueue: NexusMessage[] = [];
  private activeCycles: Map<string, FeedbackCycleResult> = new Map();
  private stats: NexusStats;
  private cycleDurations: number[] = [];

  constructor(config?: NexusCoordinatorConfig) {
    super();
    
    this.config = {
      verbose: config?.verbose ?? false,
      maxConcurrentCycles: config?.maxConcurrentCycles ?? 4,
      patchTimeout: config?.patchTimeout ?? 30000,
      autoValidate: config?.autoValidate ?? true,
      minSeverityForLoop: config?.minSeverityForLoop ?? 'medium',
      aiModel: config?.aiModel ?? 'local',
    };

    this.stats = {
      vulnerabilitiesProcessed: 0,
      testsGenerated: 0,
      patchesGenerated: 0,
      validatedPatches: 0,
      activeCycles: 0,
      avgCycleDuration: 0,
      uptime: 0,
    };
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 🚀 LIFECYCLE
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Start the Nexus Coordinator
   */
  async start(): Promise<void> {
    if (this.isRunning) return;

    this.log('🔗 Nexus Coordinator starting...');
    this.isRunning = true;
    this.startTime = Date.now();
    
    this.emit('started', { timestamp: new Date() });
    this.log('🔗 Nexus Coordinator is now active');
  }

  /**
   * Stop the Nexus Coordinator
   */
  async stop(): Promise<void> {
    if (!this.isRunning) return;

    this.log('🔗 Nexus Coordinator stopping...');
    this.isRunning = false;
    
    // Wait for active cycles to complete
    if (this.activeCycles.size > 0) {
      this.log(`Waiting for ${this.activeCycles.size} active cycles...`);
    }
    
    this.emit('stopped', { timestamp: new Date() });
    this.log('🔗 Nexus Coordinator stopped');
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 🔄 AUTONOMOUS FEEDBACK LOOP
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Process a complete feedback loop for a detected vulnerability
   * 
   * Flow:
   * 1. CyberCody detects vulnerability → Nexus receives
   * 2. Nexus triggers Shield → Generate regression test
   * 3. Nexus triggers Surgeon → Generate security patch
   * 4. Nexus validates patch using regression test
   * 5. Return complete cycle result
   */
  async processFeedbackLoop(vulnerability: DetectedVulnerability): Promise<FeedbackCycleResult> {
    const cycleId = this.generateCycleId();
    const cycleStart = Date.now();

    this.log(`🔄 Starting feedback loop ${cycleId} for ${vulnerability.type}`);
    this.stats.vulnerabilitiesProcessed++;
    this.stats.activeCycles++;
    
    this.emit('cycleStarted', { cycleId, vulnerability });

    try {
      // Check if severity meets threshold
      if (!this.meetsSeverityThreshold(vulnerability.severity)) {
        this.log(`Skipping ${cycleId}: severity ${vulnerability.severity} below threshold`);
        const skippedResult = this.createSkippedResult(cycleId, vulnerability);
        return skippedResult;
      }

      // Step 1: Generate regression test (Shield)
      const regressionTest = await this.generateRegressionTest(vulnerability);
      this.stats.testsGenerated++;
      this.log(`✅ Regression test generated: ${regressionTest.id}`);
      
      this.emit('testGenerated', { cycleId, test: regressionTest });

      // Step 2: Generate security patch (Surgeon)
      const securityPatch = await this.generateSecurityPatch(vulnerability);
      this.stats.patchesGenerated++;
      this.log(`✅ Security patch generated: ${securityPatch.id}`);
      
      this.emit('patchGenerated', { cycleId, patch: securityPatch });

      // Step 3: Validate patch (optional)
      let patchValidated = false;
      if (this.config.autoValidate) {
        patchValidated = await this.validatePatch(securityPatch, regressionTest);
        if (patchValidated) {
          this.stats.validatedPatches++;
          this.log(`✅ Patch validated successfully`);
        } else {
          this.log(`❌ Patch validation failed`);
        }
      }

      // Complete cycle
      const duration = Date.now() - cycleStart;
      this.cycleDurations.push(duration);
      this.updateAvgDuration();
      
      const result: FeedbackCycleResult = {
        cycleId,
        vulnerability,
        regressionTest,
        securityPatch,
        patchValidated,
        duration,
        completedAt: new Date(),
      };

      this.activeCycles.set(cycleId, result);
      this.stats.activeCycles--;
      
      this.emit('cycleCompleted', result);
      this.log(`🔄 Feedback loop ${cycleId} completed in ${duration}ms`);

      return result;

    } catch (error) {
      this.stats.activeCycles--;
      const errorMsg = error instanceof Error ? error.message : String(error);
      this.emit('cycleError', { cycleId, error: errorMsg });
      throw new Error(`Feedback loop ${cycleId} failed: ${errorMsg}`);
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 🛡️ SHIELD - REGRESSION TEST GENERATION
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Generate a regression test for a vulnerability
   */
  private async generateRegressionTest(vulnerability: DetectedVulnerability): Promise<RegressionTest> {
    const testId = `test_${vulnerability.id}_${Date.now()}`;
    
    // Generate test code based on vulnerability type
    const testCode = this.generateTestCode(vulnerability);
    const assertions = this.generateAssertions(vulnerability);

    const test: RegressionTest = {
      id: testId,
      vulnerabilityId: vulnerability.id,
      name: `Regression test for ${vulnerability.type} on ${vulnerability.target}`,
      code: testCode,
      expectedBehavior: this.getExpectedBehavior(vulnerability),
      assertions,
      generatedAt: new Date(),
    };

    // Send message to Shield agent
    this.sendMessage({
      id: this.generateMessageId(),
      from: 'oracle',
      to: 'shield',
      type: 'test',
      payload: test,
      priority: this.getPriorityFromSeverity(vulnerability.severity),
      timestamp: new Date(),
    });

    return test;
  }

  /**
   * Generate test code for a specific vulnerability type
   */
  private generateTestCode(vulnerability: DetectedVulnerability): string {
    const { type, target, payload, method } = vulnerability;
    
    const baseTemplate = `
import { test, expect } from '@playwright/test';

/**
 * Regression Test: ${type.toUpperCase()} vulnerability
 * Target: ${target}
 * Generated by Nexus Coordinator
 */
test('should prevent ${type} attack on ${target}', async ({ page, request }) => {
  // Setup: Navigate to target
  ${this.getNavigationCode(target)}

  // Attack: Attempt ${type} with malicious payload
  ${this.getAttackCode(type, target, payload, method)}

  // Assert: Verify attack is blocked
  ${this.getAssertionCode(type)}
});`;

    return baseTemplate.trim();
  }

  private getNavigationCode(target: string): string {
    if (target.startsWith('/api')) {
      return `// API endpoint - no navigation needed`;
    }
    return `await page.goto('${target}');`;
  }

  private getAttackCode(type: VulnerabilityType, target: string, payload: string, method: string): string {
    const escapedPayload = payload.replace(/'/g, "\\'");
    
    switch (type) {
      case 'sqli':
        return `
  const response = await request.${method.toLowerCase()}('${target}', {
    data: { input: '${escapedPayload}' }
  });`;
      case 'xss':
        return `
  await page.fill('input[type="text"]', '${escapedPayload}');
  await page.click('button[type="submit"]');`;
      case 'bola':
      case 'idor':
        return `
  const response = await request.${method.toLowerCase()}('${target}', {
    headers: { 'Authorization': 'Bearer <user_token>' }
  });`;
      default:
        return `
  const response = await request.${method.toLowerCase()}('${target}', {
    data: '${escapedPayload}'
  });`;
    }
  }

  private getAssertionCode(type: VulnerabilityType): string {
    switch (type) {
      case 'sqli':
        return `
  // SQL error messages should not be exposed
  expect(response.status()).not.toBe(500);
  const body = await response.text();
  expect(body).not.toContain('SQL syntax');
  expect(body).not.toContain('mysql_fetch');`;
      case 'xss':
        return `
  // Malicious script should be sanitized
  const pageContent = await page.content();
  expect(pageContent).not.toContain('<script>');
  expect(pageContent).not.toContain('javascript:');`;
      case 'bola':
      case 'idor':
        return `
  // Unauthorized access should be denied
  expect(response.status()).toBe(403);`;
      default:
        return `
  // Attack should be blocked
  expect(response.status()).not.toBe(200);`;
    }
  }

  private generateAssertions(vulnerability: DetectedVulnerability): string[] {
    const assertions: string[] = [];
    
    switch (vulnerability.type) {
      case 'sqli':
        assertions.push('No SQL error messages exposed');
        assertions.push('Request properly sanitized');
        assertions.push('Parameterized queries used');
        break;
      case 'xss':
        assertions.push('Script tags sanitized');
        assertions.push('HTML entities encoded');
        assertions.push('CSP headers present');
        break;
      case 'bola':
      case 'idor':
        assertions.push('Authorization check enforced');
        assertions.push('Object ownership validated');
        assertions.push('Returns 403 for unauthorized');
        break;
      default:
        assertions.push('Attack vector blocked');
        assertions.push('No sensitive data leaked');
    }

    return assertions;
  }

  private getExpectedBehavior(vulnerability: DetectedVulnerability): string {
    switch (vulnerability.type) {
      case 'sqli':
        return 'Application should reject SQL injection payloads and return sanitized responses';
      case 'xss':
        return 'Application should sanitize user input and prevent script execution';
      case 'bola':
      case 'idor':
        return 'Application should enforce authorization checks before granting access';
      case 'csrf':
        return 'Application should validate CSRF tokens on state-changing requests';
      case 'ssrf':
        return 'Application should validate and restrict server-side requests';
      default:
        return 'Application should block the attack and maintain security posture';
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 🔧 SURGEON - SECURITY PATCH GENERATION
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Generate a security patch for a vulnerability
   */
  private async generateSecurityPatch(vulnerability: DetectedVulnerability): Promise<SecurityPatch> {
    const patchId = `patch_${vulnerability.id}_${Date.now()}`;
    
    const { originalCode, patchedCode } = this.generatePatchCode(vulnerability);

    const patch: SecurityPatch = {
      id: patchId,
      vulnerabilityId: vulnerability.id,
      filePath: this.inferFilePath(vulnerability.target),
      originalCode,
      patchedCode,
      description: this.generatePatchDescription(vulnerability),
      validated: false,
      generatedAt: new Date(),
    };

    // Send message to Surgeon agent
    this.sendMessage({
      id: this.generateMessageId(),
      from: 'oracle',
      to: 'surgeon',
      type: 'patch',
      payload: patch,
      priority: this.getPriorityFromSeverity(vulnerability.severity),
      timestamp: new Date(),
    });

    return patch;
  }

  private generatePatchCode(vulnerability: DetectedVulnerability): { originalCode: string; patchedCode: string } {
    switch (vulnerability.type) {
      case 'sqli':
        return {
          originalCode: `
// VULNERABLE CODE
const query = \`SELECT * FROM users WHERE id = '\${userId}'\`;
const result = await db.query(query);`,
          patchedCode: `
// PATCHED CODE - Parameterized query
const query = 'SELECT * FROM users WHERE id = $1';
const result = await db.query(query, [userId]);`,
        };
      case 'xss':
        return {
          originalCode: `
// VULNERABLE CODE
element.innerHTML = userInput;`,
          patchedCode: `
// PATCHED CODE - HTML encoding
import { escapeHtml } from './utils/sanitizer';
element.textContent = escapeHtml(userInput);`,
        };
      case 'bola':
      case 'idor':
        return {
          originalCode: `
// VULNERABLE CODE
app.get('/api/user/:id', async (req, res) => {
  const user = await User.findById(req.params.id);
  res.json(user);
});`,
          patchedCode: `
// PATCHED CODE - Authorization check
app.get('/api/user/:id', authenticate, async (req, res) => {
  if (req.user.id !== req.params.id && !req.user.isAdmin) {
    return res.status(403).json({ error: 'Forbidden' });
  }
  const user = await User.findById(req.params.id);
  res.json(user);
});`,
        };
      default:
        return {
          originalCode: '// Original vulnerable code',
          patchedCode: '// Patched secure code',
        };
    }
  }

  private inferFilePath(target: string): string {
    // Infer file path from target endpoint
    if (target.startsWith('/api/')) {
      const parts = target.replace('/api/', '').split('/');
      return `src/routes/${parts[0]}.ts`;
    }
    return 'src/handlers/vulnerable-handler.ts';
  }

  private generatePatchDescription(vulnerability: DetectedVulnerability): string {
    return `Security patch for ${vulnerability.type.toUpperCase()} vulnerability.
    
Target: ${vulnerability.target}
Severity: ${vulnerability.severity.toUpperCase()}
CVSS Score: ${vulnerability.cvssScore}
${vulnerability.cweId ? `CWE Reference: ${vulnerability.cweId}` : ''}

This patch addresses the vulnerability by implementing proper security controls.`;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // ✅ PATCH VALIDATION
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Validate a security patch using the regression test
   */
  private async validatePatch(patch: SecurityPatch, test: RegressionTest): Promise<boolean> {
    this.log(`Validating patch ${patch.id} with test ${test.id}...`);
    
    // Send validation message
    this.sendMessage({
      id: this.generateMessageId(),
      from: 'oracle',
      to: 'shield',
      type: 'validation',
      payload: { patch, test },
      priority: 'high',
      timestamp: new Date(),
    });

    // In a real implementation, this would:
    // 1. Apply patch to a sandbox environment
    // 2. Run regression test
    // 3. Check if test passes
    // For now, simulate validation based on patch quality
    const validationScore = this.calculateValidationScore(patch, test);
    const isValid = validationScore >= 0.85;
    
    patch.validated = isValid;
    
    this.emit('patchValidated', { 
      patchId: patch.id, 
      testId: test.id, 
      isValid, 
      score: validationScore 
    });

    return isValid;
  }

  private calculateValidationScore(patch: SecurityPatch, test: RegressionTest): number {
    let score = 0;
    
    // Check if patch code is different from original
    if (patch.patchedCode !== patch.originalCode) score += 0.3;
    
    // Check if test has meaningful assertions
    if (test.assertions.length >= 2) score += 0.2;
    
    // Check if patch includes security keywords
    const securityKeywords = ['sanitize', 'validate', 'authenticate', 'authorize', 'escape', 'encode'];
    const hasSecurityFix = securityKeywords.some(kw => 
      patch.patchedCode.toLowerCase().includes(kw)
    );
    if (hasSecurityFix) score += 0.3;
    
    // Check code quality (not too simple)
    if (patch.patchedCode.length > 50) score += 0.2;
    
    return Math.min(score, 1);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 📨 MESSAGE HANDLING
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Send a message to an agent
   */
  private sendMessage(message: NexusMessage): void {
    this.messageQueue.push(message);
    this.emit('messageSent', message);
    
    if (this.config.verbose) {
      this.log(`📨 ${message.from} → ${message.to}: ${message.type}`);
    }
  }

  /**
   * Receive a message from an agent
   */
  receiveMessage(message: NexusMessage): void {
    this.emit('messageReceived', message);
    
    if (this.config.verbose) {
      this.log(`📩 ${message.from} → ${message.to}: ${message.type}`);
    }

    // Process based on message type
    switch (message.type) {
      case 'vulnerability':
        this.handleVulnerabilityMessage(message);
        break;
      case 'test':
        this.handleTestMessage(message);
        break;
      case 'patch':
        this.handlePatchMessage(message);
        break;
      case 'validation':
        this.handleValidationMessage(message);
        break;
      case 'status':
        this.handleStatusMessage(message);
        break;
    }
  }

  private handleVulnerabilityMessage(message: NexusMessage): void {
    const vulnerability = message.payload as DetectedVulnerability;
    void this.processFeedbackLoop(vulnerability);
  }

  private handleTestMessage(message: NexusMessage): void {
    this.emit('testReceived', message.payload);
  }

  private handlePatchMessage(message: NexusMessage): void {
    this.emit('patchReceived', message.payload);
  }

  private handleValidationMessage(message: NexusMessage): void {
    this.emit('validationReceived', message.payload);
  }

  private handleStatusMessage(message: NexusMessage): void {
    this.emit('statusReceived', { from: message.from, status: message.payload });
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 📊 STATISTICS & STATUS
  // ═══════════════════════════════════════════════════════════════════════════

  /**
   * Get Nexus Coordinator statistics
   */
  getStats(): NexusStats {
    return {
      ...this.stats,
      uptime: this.isRunning ? Date.now() - this.startTime : 0,
    };
  }

  /**
   * Check if coordinator is running
   */
  isActive(): boolean {
    return this.isRunning;
  }

  /**
   * Get pending messages count
   */
  getPendingMessages(): number {
    return this.messageQueue.length;
  }

  /**
   * Get active cycles count
   */
  getActiveCyclesCount(): number {
    return this.activeCycles.size;
  }

  /**
   * Get completed cycle by ID
   */
  getCycle(cycleId: string): FeedbackCycleResult | undefined {
    return this.activeCycles.get(cycleId);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // 🛠️ UTILITY METHODS
  // ═══════════════════════════════════════════════════════════════════════════

  private generateCycleId(): string {
    return `cycle_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  private generateMessageId(): string {
    return `msg_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
  }

  private meetsSeverityThreshold(severity: VulnerabilitySeverity): boolean {
    const severityOrder: VulnerabilitySeverity[] = ['info', 'low', 'medium', 'high', 'critical'];
    const vulnerabilitySeverityIndex = severityOrder.indexOf(severity);
    const thresholdIndex = severityOrder.indexOf(this.config.minSeverityForLoop);
    return vulnerabilitySeverityIndex >= thresholdIndex;
  }

  private getPriorityFromSeverity(severity: VulnerabilitySeverity): 'critical' | 'high' | 'normal' | 'low' {
    switch (severity) {
      case 'critical': return 'critical';
      case 'high': return 'high';
      case 'medium': return 'normal';
      default: return 'low';
    }
  }

  private updateAvgDuration(): void {
    if (this.cycleDurations.length > 0) {
      const sum = this.cycleDurations.reduce((a, b) => a + b, 0);
      this.stats.avgCycleDuration = Math.round(sum / this.cycleDurations.length);
    }
  }

  private createSkippedResult(cycleId: string, vulnerability: DetectedVulnerability): FeedbackCycleResult {
    return {
      cycleId,
      vulnerability,
      regressionTest: {
        id: 'skipped',
        vulnerabilityId: vulnerability.id,
        name: 'Skipped - Below severity threshold',
        code: '',
        expectedBehavior: '',
        assertions: [],
        generatedAt: new Date(),
      },
      securityPatch: {
        id: 'skipped',
        vulnerabilityId: vulnerability.id,
        filePath: '',
        originalCode: '',
        patchedCode: '',
        description: 'Skipped - Below severity threshold',
        validated: false,
        generatedAt: new Date(),
      },
      patchValidated: false,
      duration: 0,
      completedAt: new Date(),
    };
  }

  private log(message: string): void {
    if (this.config.verbose) {
      console.log(`[NEXUS] ${message}`);
    }
  }
}

// ═══════════════════════════════════════════════════════════════════════════════
// 📦 EXPORTS
// ═══════════════════════════════════════════════════════════════════════════════

export default NexusCoordinator;
