/**
 * @fileoverview Bug Report Generator - Automatic bug report creation
 * @module reporters/BugReportGenerator
 * @version 1.0.0-QAntum
 */

const fs = require('fs');
const path = require('path');
const https = require('https');
const { CONFIG } = require('../config/constants');

/**
 * BugReportGenerator creates detailed bug reports in Markdown and GitHub Issues
 * @class
 */
class BugReportGenerator {
    /**
     * Create a BugReportGenerator instance
     */
    constructor() {
        /** @type {Array<Object>} */
        this.steps = [];
        /** @type {Array<string>} */
        this.consoleLogs = [];
        /** @type {Array<Object>} */
        this.networkErrors = [];
    }

    /**
     * Add a step to the bug report
     * @param {string} action - Action performed
     * @param {string} result - Result of the action
     * @param {string} [screenshot] - Path to screenshot
     * @returns {void}
     */
    // Complexity: O(1)
    addStep(action, result, screenshot = null) {
        this.steps.push({
            timestamp: new Date().toISOString(),
            action,
            result,
            screenshot
        });
    }

    /**
     * Add a console log entry
     * @param {string} log - Log message
     * @returns {void}
     */
    // Complexity: O(1)
    addConsoleLog(log) {
        this.consoleLogs.push(log);
        // Keep max 100 logs to prevent memory issues
        if (this.consoleLogs.length > 100) {
            this.consoleLogs.shift();
        }
    }

    /**
     * Add a network error
     * @param {Object} error - Error details
     * @returns {void}
     */
    // Complexity: O(1)
    addNetworkError(error) {
        this.networkErrors.push({
            timestamp: new Date().toISOString(),
            ...error
        });
    }

    /**
     * Generate a Markdown bug report
     * @param {string} title - Bug title
     * @param {string} description - Bug description
     * @param {string} [severity='medium'] - Severity level
     * @returns {string} Markdown content
     */
    // Complexity: O(N) — linear scan
    generateMarkdown(title, description, severity = 'medium') {
        const severityEmoji = { 
            low: '🟢', 
            medium: '🟡', 
            high: '🔴', 
            critical: '🚨' 
        };
        
        let md = `# ${severityEmoji[severity] || '🐛'} Bug Report: ${title}\n\n`;
        md += `**Generated:** ${new Date().toISOString()}\n`;
        md += `**Severity:** ${severity.toUpperCase()}\n\n`;
        
        md += `## 📝 Description\n${description}\n\n`;
        
        md += `## 📋 Steps to Reproduce\n`;
        this.steps.forEach((step, i) => {
            md += `${i + 1}. **${step.action}**\n`;
            md += `   - Result: ${step.result}\n`;
            md += `   - Time: ${step.timestamp}\n`;
            if (step.screenshot) md += `   - Screenshot: ${step.screenshot}\n`;
        });
        
        if (this.consoleLogs.length > 0) {
            md += `\n## 🖥️ Console Logs\n\`\`\`\n`;
            md += this.consoleLogs.slice(-20).join('\n');
            md += `\n\`\`\`\n`;
        }
        
        if (this.networkErrors.length > 0) {
            md += `\n## 🌐 Network Errors\n`;
            this.networkErrors.forEach(err => {
                md += `- ${err.timestamp}: ${err.url || 'Unknown'} - ${err.message || 'Error'}\n`;
            });
        }
        
        md += `\n## 🤖 AI Analysis\n`;
        md += `*Awaiting Gemini analysis...*\n`;
        
        md += `\n---\n*Generated by QAntum v8.5 ULTIMATE*\n`;
        
        return md;
    }

    /**
     * Save bug report to file
     * @param {string} title - Bug title
     * @returns {Promise<string>} Path to saved file
     */
    // Complexity: O(1)
    async saveReport(title) {
        const sanitizedTitle = title.replace(/[^a-z0-9]/gi, '_').substring(0, 30);
        const filename = `bug_${Date.now()}_${sanitizedTitle}.md`;
        const filepath = path.join(CONFIG.BUG_REPORTS_DIR, filename);
        
        // Ensure directory exists
        if (!fs.existsSync(CONFIG.BUG_REPORTS_DIR)) {
            fs.mkdirSync(CONFIG.BUG_REPORTS_DIR, { recursive: true });
        }
        
        const content = this.generateMarkdown(title, 'Auto-detected issue during test execution');
        fs.writeFileSync(filepath, content);
        
        return filepath;
    }

    /**
     * Create a GitHub Issue
     * @param {string} title - Issue title
     * @param {string} body - Issue body (Markdown)
     * @returns {Promise<string|null>} Issue URL or null on failure
     */
    // Complexity: O(1)
    async createGitHubIssue(title, body) {
        if (!CONFIG.GITHUB_TOKEN) {
            console.log('   ⚠️ GitHub token not configured');
            return null;
        }
        
        if (!CONFIG.GITHUB_REPO || !CONFIG.GITHUB_REPO.includes('/')) {
            console.log('   ⚠️ GitHub repo not properly configured');
            return null;
        }
        
        try {
            const [owner, repo] = CONFIG.GITHUB_REPO.split('/');
            
            const data = JSON.stringify({ 
                title, 
                body, 
                labels: ['bug', 'auto-generated'] 
            });
            
            const options = {
                hostname: 'api.github.com',
                path: `/repos/${owner}/${repo}/issues`,
                method: 'POST',
                headers: {
                    'Authorization': `token ${CONFIG.GITHUB_TOKEN}`,
                    'User-Agent': 'QAntum-v8.5',
                    'Content-Type': 'application/json',
                    'Content-Length': Buffer.byteLength(data)
                }
            };
            
            return new Promise((resolve, reject) => {
                const req = https.request(options, (res) => {
                    let body = '';
                    res.on('data', chunk => body += chunk);
                    res.on('end', () => {
                        if (res.statusCode === 201) {
                            const issue = JSON.parse(body);
                            console.log(`   ✅ GitHub Issue created: ${issue.html_url}`);
                            // Complexity: O(1)
                            resolve(issue.html_url);
                        } else {
                            console.log(`   ⚠️ GitHub API error: ${res.statusCode}`);
                            // Complexity: O(1)
                            reject(new Error(`GitHub API error: ${res.statusCode} - ${body}`));
                        }
                    });
                });
                
                req.on('error', (e) => {
                    console.log(`   ⚠️ GitHub request failed: ${e.message}`);
                    // Complexity: O(1)
                    reject(e);
                });
                
                req.write(data);
                req.end();
            });
        } catch (e) {
            console.log(`   ⚠️ GitHub issue creation failed: ${e.message}`);
            return null;
        }
    }

    /**
     * Clear all recorded data
     * @returns {void}
     */
    // Complexity: O(1)
    clear() {
        this.steps = [];
        this.consoleLogs = [];
        this.networkErrors = [];
    }

    /**
     * Get a summary of recorded steps
     * @returns {Object} Summary object
     */
    // Complexity: O(N) — linear scan
    getSummary() {
        const successes = this.steps.filter(s => s.result.toLowerCase().includes('success')).length;
        const failures = this.steps.filter(s => 
            s.result.toLowerCase().includes('fail') || 
            s.result.toLowerCase().includes('error')
        ).length;
        
        return {
            totalSteps: this.steps.length,
            successes,
            failures,
            consoleLogs: this.consoleLogs.length,
            networkErrors: this.networkErrors.length
        };
    }
}

module.exports = { BugReportGenerator };
