/**
 * 💀 DUPLICATE DETECTOR & REPORT
 * Identifies exact duplicate files (same content hash) and generates
 * a dedup manifest showing which files are canonical and which are copies.
 * Does NOT delete — generates a report for the Architect to review.
 */

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

const ROOT = process.cwd();

interface DupeGroup {
    hash: string;
    size: number;
    methods: number;
    files: string[];
    canonical: string;
    copies: string[];
}

// Complexity: O(F * S) where F = files, S = avg file size
function main() {
    console.log('💀 DUPLICATE DETECTOR — DRY Enforcement\n');

    const mapPath = path.join(ROOT, 'public', 'qantum-neural-map.json');
    const data = JSON.parse(fs.readFileSync(mapPath, 'utf-8'));

    // Group by hash
    const byHash: Record<string, Array<{ path: string; methods: number; size: number }>> = {};
    for (const [k, v] of Object.entries(data.registry) as any) {
        if (!byHash[v.hash]) byHash[v.hash] = [];
        byHash[v.hash].push({ path: k, methods: v.methods, size: v.size });
    }

    const dupeGroups: DupeGroup[] = [];
    let totalWastedBytes = 0;
    let totalDuplicateFiles = 0;

    for (const [hash, files] of Object.entries(byHash)) {
        if (files.length <= 1) continue;

        // Heuristic: canonical file is the one in src/ or the shortest path
        const sorted = files.sort((a, b) => {
            const aScore = a.path.startsWith('src/') ? 0 : a.path.startsWith('core/') ? 1 : a.path.startsWith('OmniCore/') ? 2 : 10;
            const bScore = b.path.startsWith('src/') ? 0 : b.path.startsWith('core/') ? 1 : b.path.startsWith('OmniCore/') ? 2 : 10;
            if (aScore !== bScore) return aScore - bScore;
            return a.path.length - b.path.length;
        });

        const canonical = sorted[0].path;
        const copies = sorted.slice(1).map(f => f.path);

        dupeGroups.push({
            hash,
            size: files[0].size,
            methods: files[0].methods,
            files: files.map(f => f.path),
            canonical,
            copies,
        });

        totalDuplicateFiles += copies.length;
        totalWastedBytes += copies.length * files[0].size;
    }

    dupeGroups.sort((a, b) => b.size * b.copies.length - a.size * a.copies.length);

    // Generate report
    let report = `# 💀 QANTUM DUPLICATE FILE REPORT\n\n`;
    report += `> Generated: ${new Date().toISOString()}\n`;
    report += `> Engine: DRY Enforcement Scanner v1.0\n\n`;
    report += `## Summary\n\n`;
    report += `| Metric | Value |\n|---|---:|\n`;
    report += `| Duplicate Groups | **${dupeGroups.length}** |\n`;
    report += `| Total Duplicate Files | **${totalDuplicateFiles}** |\n`;
    report += `| Wasted Bytes | **${(totalWastedBytes / 1024).toFixed(1)} KB** |\n`;
    report += `| Wasted Methods (duplicated logic) | **${dupeGroups.reduce((s, g) => s + g.methods * g.copies.length, 0)}** |\n\n`;

    report += `## Duplicate Groups\n\n`;
    report += `For each group, the **canonical** file (recommended source of truth) is marked with ✅.\n`;
    report += `Copies (marked ❌) can be replaced with re-exports or symlinks.\n\n`;

    for (const group of dupeGroups) {
        report += `### Hash: \`${group.hash}\` (${group.methods} methods, ${(group.size / 1024).toFixed(1)} KB)\n\n`;
        report += `| Status | Path |\n|:---:|---|\n`;
        report += `| ✅ CANONICAL | \`${group.canonical}\` |\n`;
        for (const copy of group.copies) {
            report += `| ❌ DUPLICATE | \`${copy}\` |\n`;
        }
        report += `\n**Action:** Replace duplicates with:\n`;
        report += `\`\`\`typescript\nexport * from '${group.canonical.replace(/\.\w+$/, '')}';\n\`\`\`\n\n`;
    }

    report += `---\n\n> Generated by DRY Enforcement Scanner | Zero Entropy Policy\n`;

    const reportPath = path.join(ROOT, 'docs', 'enterprise', 'DUPLICATE_REPORT.md');
    fs.writeFileSync(reportPath, report);
    console.log(`✅ Report: ${reportPath}`);

    // Console summary
    console.log(`\n═══════════════════════════════════════`);
    console.log(`  Duplicate Groups:  ${dupeGroups.length}`);
    console.log(`  Duplicate Files:   ${totalDuplicateFiles}`);
    console.log(`  Wasted:            ${(totalWastedBytes / 1024).toFixed(1)} KB`);
    console.log(`═══════════════════════════════════════\n`);

    // Generate dedup script (but don't execute)
    let dedupScript = `#!/usr/bin/env bash\n# QANTUM DEDUP SCRIPT — Review before executing!\n# Generated: ${new Date().toISOString()}\n\n`;
    for (const group of dupeGroups) {
        for (const copy of group.copies) {
            const copyAbs = copy.replace(/\//g, path.sep);
            dedupScript += `# Canonical: ${group.canonical}\n`;
            dedupScript += `# rm "${copyAbs}"  # Uncomment to remove duplicate\n\n`;
        }
    }
    const scriptPath = path.join(ROOT, 'scripts', 'dedup-review.sh');
    fs.writeFileSync(scriptPath, dedupScript);
    console.log(`✅ Dedup script (review only): ${scriptPath}`);
}

main();
