/**
 * Visual Regression Tests
 * Screenshot comparison tests for visual regression
 * 
 * Generated by QAntum Oracle - Auto Test Factory
 * Generated at: 2026-02-26T20:44:29.962Z
 * Tests: 5
 */

import { test, expect } from '@playwright/test';


test('Visual - QAntum | Sovereign Subscription', async ({ page }) => {
  await page.goto('https://QAntum.website');
  await page.waitForLoadState('networkidle');

  await expect(page).toHaveScreenshot('QAntum-sovereign-subscription.png', {
    maxDiffPixels: 100,
    threshold: 0.1
  });
});



test('Visual - SINGULARITY DASHBOARD | Neural Core v1.0.0', async ({ page }) => {
  await page.goto('https://QAntum.website/singularity.html');
  await page.waitForLoadState('networkidle');

  await expect(page).toHaveScreenshot('singularity-dashboard-neural-core-v1-0-0.png', {
    maxDiffPixels: 100,
    threshold: 0.1
  });
});



test('Visual - ⚛️ QAntum Command Station - THE SINGULARITY', async ({ page }) => {
  await page.goto('https://QAntum.website/commands.html');
  await page.waitForLoadState('networkidle');

  await expect(page).toHaveScreenshot('QAntum-command-station-the-singularity.png', {
    maxDiffPixels: 100,
    threshold: 0.1
  });
});



test('Visual - ⚛️ QAntum Command Station - THE SINGULARITY (empire)', async ({ page }) => {
  await page.goto('https://QAntum.website/commands.html?focus=empire');
  await page.waitForLoadState('networkidle');

  await expect(page).toHaveScreenshot('QAntum-command-station-the-singularity-empire.png', {
    maxDiffPixels: 100,
    threshold: 0.1
  });
});



test('Visual - ⚛️ QAntum Command Station - THE SINGULARITY (node)', async ({ page }) => {
  await page.goto('https://QAntum.website/commands.html?focus=node');
  await page.waitForLoadState('networkidle');

  await expect(page).toHaveScreenshot('QAntum-command-station-the-singularity-node.png', {
    maxDiffPixels: 100,
    threshold: 0.1
  });
});

