/**
 * ═══════════════════════════════════════════════════════════════════════════════
 * ⚛️ QANTUM SOUL CLEANER (ABSOLUTE ENTROPY PURGER)
 * ═══════════════════════════════════════════════════════════════════════════════
 * 
 * Activated via Prime Directive: ZERO ENTROPY
 * Destroys recursive Git loops, duplicate repositories, deep node_modules,
 * and massive log files generated by old Vortex loops.
 * 
 * Usage:
 *   node tools/soul-cleaner.js --dry-run
 *   node tools/soul-cleaner.js --execute
 * 
 * @author dp | QAntum Labs
 * ═══════════════════════════════════════════════════════════════════════════════
 */

const fs = require('fs');
const path = require('path');
const { rmSync } = require('fs');

const ROOT_DIR = path.resolve(__dirname, '../');
const args = process.argv.slice(2);
const isExecute = args.includes('--execute');

const TARGETS_TO_DESTROY = [
    // 1. Recursive/Messed up legacy folders
    'src/SaaS-master',
    'QANTUM-JULES-jules-lwas-poc-13084310284656274882',
    'AETERNA_ARCHIVE',

    // 2. Heavy log files directly in root
    'sync_progress.log',
    'sync_progress_2.log',
    'sync_progress_clean.log',
    'sync_progress_final.log',
    'sync_progress_resilient.log',
    'sync_test_resilient.log',
    'sync.log',
    'outreach_err.log',
    'outreach_test_2.log',
    'test.log',
    'test-output.log'
];

// Folders that should be recursively searched and deleted ANYWHERE they exist
const RECURSIVE_TARGETS = [
    '.ascension-backup',
    'jules_session_',
    'ALLIN-feature-automation'
];

let bytesFreed = 0;
let filesRemoved = 0;
let directoriesRemoved = 0;

function formatBytes(bytes) {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

function calculateSizeRecursively(itemPath) {
    try {
        const stats = fs.statSync(itemPath);
        if (stats.isFile()) {
            return stats.size;
        } else if (stats.isDirectory()) {
            let total = 0;
            const children = fs.readdirSync(itemPath);
            for (const child of children) {
                total += calculateSizeRecursively(path.join(itemPath, child));
            }
            return total;
        }
    } catch (e) {
        return 0; // Symlink loops or permission errors
    }
    return 0;
}

function obliterate(itemPath, description) {
    if (!fs.existsSync(itemPath)) return;

    try {
        const size = calculateSizeRecursively(itemPath);
        const stats = fs.statSync(itemPath);

        console.log(`[🎯 TARGET ACQUIRED] ${description}: ${itemPath} (${formatBytes(size)})`);

        if (isExecute) {
            if (stats.isDirectory()) {
                rmSync(itemPath, { recursive: true, force: true });
                directoriesRemoved++;
            } else {
                fs.unlinkSync(itemPath);
                filesRemoved++;
            }
            console.log(`[💥 OBLITERATED] Successfully removed.`);
        } else {
            if (stats.isDirectory()) directoriesRemoved++;
            else filesRemoved++;
        }
        bytesFreed += size;
    } catch (err) {
        console.error(`[⚠️ WARNING] Failed to destroy ${itemPath}: ${err.message}`);
    }
}

function scanAndDestroyRecursively(dir) {
    try {
        const items = fs.readdirSync(dir);
        for (const item of items) {
            const itemPath = path.join(dir, item);

            // Skip actual project node_modules and .git
            if (item === 'node_modules' && dir === ROOT_DIR) continue;
            if (item === '.git') continue;

            const shouldDestroy = RECURSIVE_TARGETS.some(target => item.includes(target));

            if (shouldDestroy) {
                obliterate(itemPath, 'Recursive Entropy Pattern');
                continue; // Don't scan inside if it's going to be destroyed
            }

            try {
                if (fs.statSync(itemPath).isDirectory()) {
                    scanAndDestroyRecursively(itemPath);
                }
            } catch (e) {
                // Ignore stat errors
            }
        }
    } catch (e) {
        // Ignore read errors
    }
}

console.log(`
    🌌 SOUL CLEANER INITIATED
    ════════════════════════════════════════
    Mode: ${isExecute ? '💥 ANNIHILATION' : '👁️ CLAIRVOYANCE (DRY RUN)'}
    Root: ${ROOT_DIR}
`);

// Step 1: Specific root targets
console.log(`\n--- EXECUTING PRIMARY TARGETS ---`);
for (const target of TARGETS_TO_DESTROY) {
    const fullPath = path.join(ROOT_DIR, target);
    obliterate(fullPath, 'Primary Target');
}

// Step 2: Recursive deep scan
console.log(`\n--- SCANNING FOR DEEP ENTROPY ---`);
scanAndDestroyRecursively(ROOT_DIR);

console.log(`
    🏁 MISSION ACCOMPLISHED
    ════════════════════════════════════════
    Files targeted: ${filesRemoved}
    Directories targeted: ${directoriesRemoved}
    Entropy Mass: ${formatBytes(bytesFreed)}
`);

if (!isExecute) {
    console.log(`\n⚠️ This was a simulation. Run with --execute to commit annihilation.`);
}
