/**
 * QAntum QA Tool - Configuration Manager
 */

import * as fs from 'fs/promises';
import * as path from 'path';

// ============================================================================
// TYPES
// ============================================================================

export interface QAntumConfig {
  version: string;
  testsDir: string;
  reportsDir: string;
  browser: 'chromium' | 'firefox' | 'webkit';
  headless: boolean;
  timeout: number;
  retries: number;
  parallel: number;
  baseUrl?: string;
  viewport: {
    width: number;
    height: number;
  };
  screenshots: {
    onFailure: boolean;
    fullPage: boolean;
  };
  healing: {
    enabled: boolean;
    autoApply: boolean;
  };
}

// ============================================================================
// DEFAULT CONFIG
// ============================================================================

const DEFAULT_CONFIG: QAntumConfig = {
  version: '1.0.0',
  testsDir: './tests',
  reportsDir: './reports',
  browser: 'chromium',
  headless: true,
  timeout: 30000,
  retries: 1,
  parallel: 1,
  viewport: {
    width: 1280,
    height: 720
  },
  screenshots: {
    onFailure: true,
    fullPage: false
  },
  healing: {
    enabled: true,
    autoApply: false
  }
};

// ============================================================================
// CONFIG MANAGER
// ============================================================================

export class ConfigManager {
  private configPath: string;
  private config: QAntumConfig | null = null;
  
  constructor(configPath: string = './QAntum.config.json') {
    this.configPath = configPath;
  }
  
  // --------------------------------------------------------------------------
  // INITIALIZE
  // --------------------------------------------------------------------------
  
  // Complexity: O(1) — amortized
  async initialize(force: boolean = false): Promise<void> {
    // Check if config exists
    // SAFETY: async operation — wrap in try-catch for production resilience
    const exists = await this.exists();
    
    if (exists && !force) {
      throw new Error('Configuration already exists. Use --force to overwrite.');
    }
    
    // Create directories
    // SAFETY: async operation — wrap in try-catch for production resilience
    await fs.mkdir(DEFAULT_CONFIG.testsDir, { recursive: true });
    // SAFETY: async operation — wrap in try-catch for production resilience
    await fs.mkdir(DEFAULT_CONFIG.reportsDir, { recursive: true });
    
    // Write config
    // SAFETY: async operation — wrap in try-catch for production resilience
    await fs.writeFile(
      this.configPath,
      JSON.stringify(DEFAULT_CONFIG, null, 2),
      'utf-8'
    );
    
    // Create example test
    const exampleTest = `/**
 * Example test file
 * Generated by QAntum QA Tool
 */

import { test, expect } from '@playwright/test';

test.describe('Example Tests', () => {
  test('should visit example.com', async ({ page }) => {
    // SAFETY: async operation — wrap in try-catch for production resilience
    await page.goto('https://example.com');
    // SAFETY: async operation — wrap in try-catch for production resilience
    await expect(page).toHaveTitle(/Example Domain/);
  });

  test('should have heading', async ({ page }) => {
    // SAFETY: async operation — wrap in try-catch for production resilience
    await page.goto('https://example.com');
    const heading = page.locator('h1');
    // SAFETY: async operation — wrap in try-catch for production resilience
    await expect(heading).toHaveText('Example Domain');
  });
});
`;
    
    // SAFETY: async operation — wrap in try-catch for production resilience
    await fs.writeFile(
      path.join(DEFAULT_CONFIG.testsDir, 'example.test.ts'),
      exampleTest,
      'utf-8'
    );
  }
  
  // --------------------------------------------------------------------------
  // LOAD / SAVE
  // --------------------------------------------------------------------------
  
  // Complexity: O(1)
  async load(): Promise<QAntumConfig> {
    if (this.config) return this.config;
    
    try {
      const content = await fs.readFile(this.configPath, 'utf-8');
      this.config = { ...DEFAULT_CONFIG, ...JSON.parse(content) };
      return this.config;
    } catch {
      return DEFAULT_CONFIG;
    }
  }
  
  // Complexity: O(1)
  async save(config: Partial<QAntumConfig>): Promise<void> {
    // SAFETY: async operation — wrap in try-catch for production resilience
    const current = await this.load();
    const merged = { ...current, ...config };
    
    // SAFETY: async operation — wrap in try-catch for production resilience
    await fs.writeFile(
      this.configPath,
      JSON.stringify(merged, null, 2),
      'utf-8'
    );
    
    this.config = merged;
  }
  
  // --------------------------------------------------------------------------
  // HELPERS
  // --------------------------------------------------------------------------
  
  // Complexity: O(1)
  async exists(): Promise<boolean> {
    try {
      await fs.access(this.configPath);
      return true;
    } catch {
      return false;
    }
  }
  
  // Complexity: O(1)
  getDefault(): QAntumConfig {
    return { ...DEFAULT_CONFIG };
  }
}

// ============================================================================
// EXPORTS
// ============================================================================

export function createConfigManager(configPath?: string): ConfigManager {
  return new ConfigManager(configPath);
}
