apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: QANTUM-mind
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: QANTUM-mind.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: QANTUM-mind
                port:
                  number: 80
